<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $properties = [
            [
                'name' => 'Beachfront Villa - Malibu',
                'type' => 'Vacation Rental',
                'status' => 'Active',
                'location' => 'Malibu, California',
                'description' => 'A stunning beachfront villa with panoramic ocean views and direct beach access. Perfect for luxury getaways.',
                'amenities' => ['wifi', 'parking', 'pool', 'kitchen', 'mountain_view', 'security'],
                'house_rules' => ['No smoking', 'No pets', 'Check-in after 3 PM', 'Check-out before 11 AM', 'No unregistered guests'],
                'policies' => ['Quiet hours from 10 PM to 7 AM', 'Maximum occupancy as listed', 'No commercial photography without permission'],
                'price_format' => '$450/month',
                'images' => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                ],
                'base_price' => 450.00,
                'currency' => 'USD',
                'cleaning_fee' => 75.00,
                'service_fee' => 35.00,
                'guests' => 8,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'check_in_time' => '3:00 PM',
                'check_out_time' => '11:00 AM',
                'minimum_stay' => 3,
                'views_7d' => 156,
                'views_30d' => 623,
                'inquiries' => 8,
                'bookings' => 3,
                'rating' => 4.8,
                'reviews' => 47,
            ],
            [
                'name' => 'Downtown Loft - NYC',
                'type' => 'Short Term Rental',
                'status' => 'Active',
                'location' => 'New York, New York',
                'description' => 'Modern loft in the heart of Manhattan with stunning city views and all amenities.',
                'amenities' => ['wifi', 'kitchen', 'gym', 'security'],
                'house_rules' => ['No smoking', 'No parties', 'Check-in after 3 PM', 'Check-out before 11 AM'],
                'policies' => ['City noise ordinance applies', 'Rooftop access during daylight hours only'],
                'price_format' => '$325/month',
                'images' => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                ],
                'base_price' => 325.00,
                'currency' => 'USD',
                'cleaning_fee' => 50.00,
                'service_fee' => 25.00,
                'guests' => 4,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'check_in_time' => '3:00 PM',
                'check_out_time' => '11:00 AM',
                'minimum_stay' => 2,
                'views_7d' => 89,
                'views_30d' => 342,
                'inquiries' => 5,
                'bookings' => 2,
                'rating' => 4.6,
                'reviews' => 32,
            ],
            [
                'name' => 'Mountain Cabin - Aspen',
                'type' => 'Vacation Rental',
                'status' => 'Active',
                'location' => 'Aspen, Colorado',
                'description' => 'Cozy mountain cabin with fireplace, hot tub, and breathtaking mountain views.',
                'amenities' => ['wifi', 'parking', 'pool', 'mountain_view'],
                'house_rules' => ['No smoking', 'No loud music after 10 PM', 'Check-in after 4 PM', 'Check-out before 10 AM'],
                'policies' => ['Ski equipment storage available', 'Hot tub maintenance daily at 10 AM'],
                'price_format' => '$380/month',
                'images' => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                ],
                'base_price' => 380.00,
                'currency' => 'USD',
                'cleaning_fee' => 60.00,
                'service_fee' => 30.00,
                'guests' => 6,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'check_in_time' => '4:00 PM',
                'check_out_time' => '10:00 AM',
                'minimum_stay' => 2,
                'views_7d' => 234,
                'views_30d' => 891,
                'inquiries' => 12,
                'bookings' => 4,
                'rating' => 4.9,
                'reviews' => 58,
            ],
            [
                'name' => 'City Apartment - San Francisco',
                'type' => 'Short Term Rental',
                'status' => 'Maintenance',
                'location' => 'San Francisco, California',
                'description' => 'Stylish apartment in the Mission District with modern amenities and easy access to public transport.',
                'amenities' => ['wifi', 'kitchen', 'gym'],
                'house_rules' => ['No smoking', 'No parties', 'Check-in after 3 PM', 'Check-out before 11 AM'],
                'policies' => ['Public transportation passes available', 'Gym access 24/7'],
                'price_format' => '$275/month',
                'images' => [
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
                'base_price' => 275.00,
                'currency' => 'USD',
                'cleaning_fee' => 45.00,
                'service_fee' => 20.00,
                'guests' => 3,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'check_in_time' => '3:00 PM',
                'check_out_time' => '11:00 AM',
                'minimum_stay' => 2,
                'views_7d' => 45,
                'views_30d' => 178,
                'inquiries' => 2,
                'bookings' => 0,
                'rating' => 4.3,
                'reviews' => 19,
            ],
            [
                'name' => 'Lake House - Tahoe',
                'type' => 'Vacation Rental',
                'status' => 'Active',
                'location' => 'Lake Tahoe, California',
                'description' => 'Beautiful lakefront property with private dock, perfect for water activities and relaxation.',
                'amenities' => ['wifi', 'parking', 'pool', 'kitchen'],
                'house_rules' => ['No smoking', 'No pets', 'Check-in after 3 PM', 'Check-out before 11 AM', 'No unregistered guests'],
                'policies' => ['Lake access sunrise to sunset', 'Boat dock usage requires advance notice'],
                'price_format' => '$425/month',
                'images' => [
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                ],
                'base_price' => 425.00,
                'currency' => 'USD',
                'cleaning_fee' => 70.00,
                'service_fee' => 35.00,
                'guests' => 10,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'check_in_time' => '3:00 PM',
                'check_out_time' => '11:00 AM',
                'minimum_stay' => 3,
                'views_7d' => 178,
                'views_30d' => 567,
                'inquiries' => 7,
                'bookings' => 2,
                'rating' => 4.7,
                'reviews' => 41,
            ],
            [
                'name' => 'Desert Retreat - Palm Springs',
                'type' => 'Vacation Rental',
                'status' => 'Active',
                'location' => 'Palm Springs, California',
                'description' => 'Stylish desert retreat with private pool, mountain views, and modern amenities.',
                'amenities' => ['wifi', 'parking', 'pool', 'kitchen', 'mountain_view'],
                'house_rules' => ['No smoking', 'No pets', 'Check-in after 3 PM', 'Check-out before 11 AM'],
                'policies' => ['Pool heating available for additional fee', 'Mountain hiking trails nearby'],
                'price_format' => '$350/month',
                'images' => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                ],
                'base_price' => 350.00,
                'currency' => 'USD',
                'cleaning_fee' => 65.00,
                'service_fee' => 30.00,
                'guests' => 6,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'check_in_time' => '3:00 PM',
                'check_out_time' => '11:00 AM',
                'minimum_stay' => 2,
                'views_7d' => 123,
                'views_30d' => 445,
                'inquiries' => 6,
                'bookings' => 3,
                'rating' => 4.6,
                'reviews' => 38,
            ],
            [
                'name' => 'Historic Townhouse - Boston',
                'type' => 'Short Term Rental',
                'status' => 'Active',
                'location' => 'Boston, Massachusetts',
                'description' => 'Charming historic townhouse in the heart of Boston with modern updates and classic charm.',
                'amenities' => ['wifi', 'kitchen'],
                'house_rules' => ['No smoking', 'No parties', 'Check-in after 3 PM', 'Check-out before 11 AM'],
                'policies' => ['Historic building - please be respectful', 'Laundry facilities on-site'],
                'price_format' => '$295/month',
                'images' => [
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
                'base_price' => 295.00,
                'currency' => 'USD',
                'cleaning_fee' => 55.00,
                'service_fee' => 25.00,
                'guests' => 4,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'check_in_time' => '3:00 PM',
                'check_out_time' => '11:00 AM',
                'minimum_stay' => 2,
                'views_7d' => 67,
                'views_30d' => 234,
                'inquiries' => 4,
                'bookings' => 1,
                'rating' => 4.4,
                'reviews' => 22,
            ],
            [
                'name' => 'Coastal Cottage - Maine',
                'type' => 'Vacation Rental',
                'status' => 'Seasonal',
                'location' => 'Bar Harbor, Maine',
                'description' => 'Quaint coastal cottage with ocean views, perfect for a peaceful getaway.',
                'amenities' => ['wifi', 'kitchen'],
                'house_rules' => ['No smoking', 'No pets', 'Check-in after 4 PM', 'Check-out before 10 AM'],
                'policies' => ['Seasonal property - closed during winter months', 'Beach access via private path'],
                'price_format' => '$275/month',
                'images' => [
                    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                ],
                'base_price' => 275.00,
                'currency' => 'USD',
                'cleaning_fee' => 50.00,
                'service_fee' => 20.00,
                'guests' => 4,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'check_in_time' => '4:00 PM',
                'check_out_time' => '10:00 AM',
                'minimum_stay' => 3,
                'views_7d' => 34,
                'views_30d' => 89,
                'inquiries' => 1,
                'bookings' => 0,
                'rating' => 4.2,
                'reviews' => 15,
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
